appmnemonic       = "nowe"
location          = "eastus"
environment       = "dev"
functional_area   = "global services"
data_product_name = "Service Management"
admin_member = "harish@rgtechlabsoutlook.onmicrosoft.com"
dev_member = "naresh@rgtechlabsoutlook.onmicrosoft.com"
