databricks_workspace_name = ""
databricks_account_id = ""
existing_datalake = ""
appmnemonic = ""
environment = ""
functional_area = ""
data_product_name = ""
ad_admins_group = ""
ad_developers_group = ""
service_principal = ""
datafactory = ""
keyvault = ""
subscription_id = ""
#schma readers group for synapse