name: IaC SAST Scan

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Security_Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pre-commit
          
      - name: Install pre-commit
        run: pip install pre-commit

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov --quiet --compact -d .
        continue-on-error: true

      - name: Save Checkov exit code to file
        run: echo $? > CHVEXIT

      - name: Display Checkov exit code
        run: cat CHVEXIT
